### ISSUE TITLE
Add 'Haddock' phase

### ISSUE THREAD

**Issue by chshersh** [chshersh/dr-cabal#10]
When building dependencies, you can ask `cabal` to also build their documentation. This is represented by the `Haddock` step in the output like this:

```
Building     base-orphans-0.8.6 (lib)
Haddock      base-orphans-0.8.6 (lib)
Installing   base-orphans-0.8.6 (lib)
Completed    base-orphans-0.8.6 (lib)
```

Currently, this phase is not supported by `dr-cabal` but it should be pretty straightforward to add it. Implementation plan:

1. Add new `Haddock` status here:

https://github.com/chshersh/dr-cabal/blob/89cdcd6ed7714e0b177522eae136ce9e8749ebb3/src/DrCabal/Model.hs#L24-L31

2. Add the new phase here:

https://github.com/chshersh/dr-cabal/blob/89cdcd6ed7714e0b177522eae136ce9e8749ebb3/src/DrCabal/Profile.hs#L73-L78

3. Update phases calculation:

https://github.com/chshersh/dr-cabal/blob/89cdcd6ed7714e0b177522eae136ce9e8749ebb3/src/DrCabal/Profile.hs#L86

4. Update legend:

https://github.com/chshersh/dr-cabal/blob/89cdcd6ed7714e0b177522eae136ce9e8749ebb3/src/DrCabal/Profile.hs#L143-L151

5. Update profile output:

https://github.com/chshersh/dr-cabal/blob/89cdcd6ed7714e0b177522eae136ce9e8749ebb3/src/DrCabal/Profile.hs#L172-L179

**Comment by diasbruno** [comment]
@chshersh I'd like to contribute. Already start working on this one?
