### ISSUE TITLE
Suggest cabal --store-dir

### ISSUE THREAD

**Issue by Bodigrim** [chshersh/dr-cabal#26]
https://github.com/chshersh/dr-cabal/blob/af95d44e5294719a8cb888a8de10594f9f8c0464/README.md?plain=1#L102-L107

I'd like to suggest an even less intrusive approach, without nuking the whole `store`: 

```
cabal --store-dir=foobar build
```

Cabal will create if non-existent and use `foobar` folder to store built packages. 

POSIX users can simplify their lifes even further, creating a fresh temporary folder every time:

```
cabal --store-dir=$(mktemp -d) build
```

**Comment by chshersh** [comment]
That sounds like a great suggestion and a really nice documentation improvement 🙂
